### PR TITLE
support $$ as a way to escape $

### PR DESCRIPTION
**Pull request by bjaglin**
Fixes https://github.com/michaelsauter/crane/issues/51

docker-compose has the [same behavior](https://docs.docker.com/compose/compose-file/#variable-substitution) as of 1.5.0. I am not particularly proud of the implementation, but it does the job and removes this annoying limitation.

### CODE REVIEW

**Comment by michaelsauter** [comment]
Looks good.

Could you update this once the networks/volumes branch is merged?

I think then it's time for another release - probably after Christmas but before the new year!

**Comment by bjaglin** [comment]
I'll rebase and add an entry in the changelog once the other PR is merged.

**Comment by michaelsauter** [comment]
@bjaglin OK, if you could rebase that would be great now that the networks and volumes stuff is merged. Would be great to add a comment to the changeling too.

**Comment by bjaglin** [comment]
@michaelsauter done

**Pull request merged**
