### PR TITLE
Docker 1.5 flags

### PR DESCRIPTION
**Pull request by bjaglin**
Tested against Docker 1.5.0-rc2

### CODE REVIEW

**Comment by dreamcat4** [comment]
+1. I need this too.

**Comment by dreamcat4** [comment]
@bjaglin - Did I do it right? I've tried to put `pid: host` in the run options of crane.yml, but it hasn't seemed to work. My config file looks like this:

```
  pipework:
    image: dreamcat4/pipework
    dockerfile: pipework
    run:
      volume:
        - /var/run/docker.sock:/docker.sock
      privileged: true
      pid: host
      link:
        - tvheadend:tvheadend
```

I've already installed docker-1.5.0 from the ubuntu testing repository. Confirmed that same image works otherwise on cmd line with `docker run --pid=host …`. Where it sees the host processes.

Did you test new `--pid` option specifically, or just the other 2 ones?

**Comment by dreamcat4** [comment]
@bjaglin ah, never mind. Checked your code which looked OK. It seems I didn't compile locally properly. It pulled in the official version and dumped it in src/ subdirectory…

If you could please give me a better build instructions. What I did previously (which has gotta be wrong somewhere) was this:

	sudo apt-get install gccgo-go
	git clone https://github.com/bjaglin/crane.git crane-docker15flags
	cd crane-docker15flags
	git checkout -b docker15flags origin/docker15flags
	GOPATH=$PWD go get # ignore the error message
	GOPATH=$PWD go build
	./crane-docker15flags
	ln -s $PWD/crane-docker15flags /usr/local/sbin/crane-docker15flags

**Comment by michaelsauter** [comment]
@bjaglin Thanks again!

@dreamcat4 Merged into master, so this should be a lot easier to build :)

**Pull request merged**
