### PR TITLE
WIP Kingpin

### PR DESCRIPTION
**Pull request by michaelsauter**
Very ugly at this stage, and non-functional. 

**EDIT: This is probably becoming Crane 2.0, see below.**

### CODE REVIEW

**Comment by michaelsauter** [comment]
This is turning into something like a "2.0" branch :)

* Changed semantics of run / start (replace recreate flag)
* Single target only
* Automatic resolution and handling of dependencies
* Extension of target to affected containers and/or dependencies (replace current cascade flags)
* Randomly named containers
* [Still to come] Ad-hoc cmd for run
* [Still to come] Exclude groups/containers (replace ignore missing flag)

**Comment by michaelsauter** [comment]
This should be functional now, plus it has added support for:

* Ad-hoc cmd for run
* Exclude groups/containers (remove need for ignore-missing flag)

Would be interesting to get some user feedback on this. Might need to release that as 2.0 beta, once there CI is green again.

**Comment by utaal** [comment]
Happy to help test this. I'm going to try and depend on the new api for our internal CI project and report back.

**Comment by michaelsauter** [comment]
@utaal Awesome! Looking forward to what you think.

**Comment by michaelsauter** [comment]
Closed in favour of #212.

**Pull request closed without merging**
