### PR TITLE
Run flags walkthrough

### PR DESCRIPTION
**Pull request by bjaglin**
https://github.com/michaelsauter/crane/commit/306af735838f90608f5c4abe6e48fbf3bd8dfb10 turned out to be more challenging than the others, and undercovered a bug (see commit description)

### CODE REVIEW

**Comment by michaelsauter** [comment]
Thanks for that and the fix to the net flag!

**Comment by bjaglin** [comment]
Coincidence - the regression is actually hitting us as we need this feature now... Any chance you could cut out a release?

**Comment by michaelsauter** [comment]
Will do tonight. In theory you could do it as well with the release script, but I'm also signing the releases at the moment. Not sure how to go about that. 

Will be 2.3.0 then.

**Comment by michaelsauter** [comment]
@bjaglin Done: https://github.com/michaelsauter/crane/blob/master/CHANGELOG.md#230-2015-12-09

**Pull request merged**
